# Generated by Django 3.2.6 on 2021-08-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='usuario',
            new_name='users',
        ),
    ]
